/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Jobs
         * @description Deleted jobs are excluded unless status=deleted is explicitly requested.
         */
        get: operations["list_jobs_jobs_get"];
        put?: never;
        post?: never;
        /**
         * Delete Jobs Before
         * @description Hard delete (carried over from v1's explicit design: this bulk-cleanup
         *     action removes rows outright, unlike DELETE /jobs/{id}'s soft delete) —
         *     cannot be undone.
         */
        delete: operations["delete_jobs_before_jobs_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job Stats */
        get: operations["job_stats_jobs_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/count-before": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Count Jobs Before
         * @description Preview how many jobs DELETE /jobs?before_date=... would remove, without deleting anything.
         */
        get: operations["count_jobs_before_jobs_count_before_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_jobs__job_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Job
         * @description Soft delete (status="deleted") — carried over from v1: hides the job
         *     from results but keeps the row so a future scrape of the same link
         *     doesn't silently resurface it.
         */
        delete: operations["delete_job_jobs__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Job Status */
        patch: operations["update_job_status_jobs__job_id__status_patch"];
        trace?: never;
    };
    "/scrape": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Scrape
         * @description Enqueues run_scrape_task for one pipeline — 202 Accepted with a job_id;
         *     poll GET /scrape/runs?pipeline_id= for progress (FR-1A.6). Triggering
         *     works regardless of the pipeline's `enabled` flag — that flag only gates
         *     the (future) scheduler, not a manual trigger.
         */
        post: operations["trigger_scrape_scrape_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scrape/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Scrape Runs */
        get: operations["list_scrape_runs_scrape_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scrape/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scrape Run */
        get: operations["get_scrape_run_scrape__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scrape/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Scrape Run
         * @description Best-effort, cooperative stop (Pipelines page "Stop" action) — raises
         *     `cancel_requested`, which the running scrape loop notices between
         *     batches (scrape_service.py), not instantly. 409 if the run isn't
         *     currently `running` (already finished — nothing to cancel).
         */
        post: operations["cancel_scrape_run_scrape__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resumes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Resumes */
        get: operations["list_resumes_resumes_get"];
        put?: never;
        /** Create Resume */
        post: operations["create_resume_resumes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resumes/{resume_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Resume */
        get: operations["get_resume_resumes__resume_id__get"];
        /**
         * Update Resume
         * @description Rename, replace the PDF, or both. Replacing the PDF re-extracts text
         *     and clears the cached ResumeProfile (Repository.update_resume), then
         *     re-parses immediately (same eager-parse-at-upload-time behavior as
         *     POST /resumes) rather than leaving the resume unparsed until whatever
         *     pipeline run uses it next.
         */
        put: operations["update_resume_resumes__resume_id__put"];
        post?: never;
        /** Delete Resume */
        delete: operations["delete_resume_resumes__resume_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pipelines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Pipelines */
        get: operations["list_pipelines_pipelines_get"];
        put?: never;
        /** Create Pipeline */
        post: operations["create_pipeline_pipelines_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pipelines/{pipeline_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Pipeline */
        get: operations["get_pipeline_pipelines__pipeline_id__get"];
        /** Update Pipeline */
        put: operations["update_pipeline_pipelines__pipeline_id__put"];
        post?: never;
        /** Delete Pipeline */
        delete: operations["delete_pipeline_pipelines__pipeline_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pipelines/{pipeline_id}/rejected-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Rejected Jobs
         * @description FR-2.3 audit trail — why jobs didn't pass this pipeline's filter.
         */
        get: operations["list_rejected_jobs_pipelines__pipeline_id__rejected_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pipelines/{pipeline_id}/scrape-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Clear Scrape Runs
         * @description Pipelines page "clear run history" action. Never touches a
         *     currently-`running` run (Repository.delete_scrape_runs) — deletes
         *     everything else, and the RejectedJob audit rows that belonged to those
         *     runs go with them (cascade), while jobs those runs saved keep existing,
         *     just losing their run attribution.
         */
        delete: operations["clear_scrape_runs_pipelines__pipeline_id__scrape_runs_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/llm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Llm Setting
         * @description Falls back to the env-configured default if no LLMSetting row has
         *     been created yet (first boot, before PUT has ever been called).
         */
        get: operations["get_llm_setting_settings_llm_get"];
        /**
         * Update Llm Setting
         * @description Takes effect on the very next get_llm() call — a new scrape run's
         *     extraction and any on-demand feature call both pick it up with no
         *     container restart (Phase 5 exit criterion, plan.md).
         */
        put: operations["update_llm_setting_settings_llm_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/scraper-credentials/{site}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scraper Credential
         * @description Never returns the full cookie value — `masked_value` (last 4 chars)
         *     plus the last check's result/timestamp is enough for the UI to show
         *     what's stored without exposing the working credential.
         */
        get: operations["get_scraper_credential_settings_scraper_credentials__site__get"];
        /**
         * Update Scraper Credential
         * @description Takes effect on the very next scrape run for this site — no worker
         *     restart (the previous LI_AT_COOKIE-env-only setup needed one to rotate
         *     an expired cookie).
         *
         *     Also auto-enqueues a validity check (check_scraper_credential_task) right
         *     away — per explicit user feedback, saving a cookie and finding out
         *     whether it actually works shouldn't be two separate steps. The response
         *     still comes back with last_check_status=null (the check runs on the
         *     worker, in the background); the frontend's poll on GET picks up the
         *     result a few seconds later, same as it already did for the standalone
         *     "Test cookie" action this replaces.
         */
        put: operations["update_scraper_credential_settings_scraper_credentials__site__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/features/{feature}/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run On Demand Feature
         * @description FR-6.2: synchronous on-demand feature call (button click -> loading
         *     state -> result), no queue. FR-6.3: cached per (job, resume, feature,
         *     params) — a second identical request is served from the cache without a
         *     new LLM call, unless `regenerate: true` is passed.
         *
         *     Known features (see feature_service.FEATURES for the authoritative
         *     list/params): cover_letter (tone), interview_prep, company_research (no
         *     resume needed), resume_improvement, referral_message (channel,
         *     contact_name, contact_title), negotiation_prep.
         */
        post: operations["run_on_demand_feature_features__feature___job_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/export/csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Csv */
        get: operations["export_csv_export_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/export/excel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Excel
         * @description 3 sheets: Matched Jobs (colour-coded by score), Skill Gaps (missing-skill
         *     frequency across the exported jobs), Status Board (status funnel).
         */
        get: operations["export_excel_export_excel_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Verifies API, DB, and Redis are all reachable — architecture.md §2 exit
         *     criteria for Phase 0.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_create_resume_resumes_post */
        Body_create_resume_resumes_post: {
            /** Name */
            name: string;
            /** File */
            file: string;
        };
        /** Body_update_resume_resumes__resume_id__put */
        Body_update_resume_resumes__resume_id__put: {
            /** Name */
            name?: string | null;
            /** File */
            file?: string | null;
        };
        /** BulkDeleteResponse */
        BulkDeleteResponse: {
            /** Deleted Count */
            deleted_count: number;
            /** Before Date */
            before_date: string;
        };
        /** DeletedCountResponse */
        DeletedCountResponse: {
            /** Deleted Count */
            deleted_count: number;
        };
        /** FeatureRequestBody */
        FeatureRequestBody: {
            /** Tone */
            tone?: string | null;
            /** Channel */
            channel?: string | null;
            /** Contact Name */
            contact_name?: string | null;
            /** Contact Title */
            contact_title?: string | null;
            /**
             * Regenerate
             * @default false
             */
            regenerate: boolean;
        };
        /** FeatureRunResponse */
        FeatureRunResponse: {
            /** Feature */
            feature: string;
            /** Job Id */
            job_id: string;
            /** Params */
            params: {
                [key: string]: unknown;
            };
            /** Cached */
            cached: boolean;
            /** Result */
            result: {
                [key: string]: unknown;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Db */
            db: string;
            /** Redis */
            redis: string;
            /** Version */
            version: string;
        };
        /** JobCountResponse */
        JobCountResponse: {
            /** Count */
            count: number;
            /** Before Date */
            before_date: string;
        };
        /** JobResponse */
        JobResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Company */
            company: string;
            /** Location */
            location: string | null;
            /** Link */
            link: string;
            /** Apply Link */
            apply_link: string | null;
            /** Description */
            description: string | null;
            /** Skills Required */
            skills_required: string[] | null;
            /** Skills Nice To Have */
            skills_nice_to_have: string[] | null;
            /** Experience Years Min */
            experience_years_min: number | null;
            /** Seniority Level */
            seniority_level: string | null;
            /** Employment Type */
            employment_type: string | null;
            /** Remote Policy */
            remote_policy: string | null;
            /** Education Required */
            education_required: string | null;
            /** Match Score */
            match_score: number | null;
            /** Matched Skills */
            matched_skills: string[] | null;
            /** Missing Skills */
            missing_skills: string[] | null;
            /** Match Rationale */
            match_rationale: string | null;
            /** Scored With Resume Id */
            scored_with_resume_id: string | null;
            /**
             * Pipeline Id
             * Format: uuid
             */
            pipeline_id: string;
            /** Scrape Run Id */
            scrape_run_id: string | null;
            /** Source Site */
            source_site: string;
            /** Status */
            status: string;
            /** Salary Benchmark */
            salary_benchmark: {
                [key: string]: unknown;
            } | null;
            /** Salary Enrichment Status */
            salary_enrichment_status: string;
            /** Date Posted */
            date_posted: string | null;
            /**
             * Scraped At
             * Format: date-time
             */
            scraped_at: string;
            /** Updated At */
            updated_at: string | null;
        };
        /** JobStatsResponse */
        JobStatsResponse: {
            /** Total Jobs */
            total_jobs: number;
            /** With Description */
            with_description: number;
            /** With Match Score */
            with_match_score: number;
            /** Avg Match Score */
            avg_match_score: number;
        };
        /** JobStatusUpdateRequest */
        JobStatusUpdateRequest: {
            /**
             * Status
             * @description new | saved | applied | interview | offer | rejected
             */
            status: string;
        };
        /** JobStatusUpdateResponse */
        JobStatusUpdateResponse: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Status */
            status: string;
            /** Updated */
            updated: boolean;
        };
        /** LLMSettingResponse */
        LLMSettingResponse: {
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /** Temperature */
            temperature: number;
            /** Max Tokens */
            max_tokens: number;
        };
        /** LLMSettingUpdateRequest */
        LLMSettingUpdateRequest: {
            /**
             * Provider
             * @default bedrock
             */
            provider: string;
            /** Model */
            model: string;
            /**
             * Temperature
             * @default 0.1
             */
            temperature: number;
            /**
             * Max Tokens
             * @default 2000
             */
            max_tokens: number;
        };
        /** PipelineCreateRequest */
        PipelineCreateRequest: {
            /** Name */
            name: string;
            /** Site */
            site: string;
            /** Query */
            query: string;
            /** Locations */
            locations?: string[];
            /** Filters */
            filters?: {
                [key: string]: unknown;
            };
            /** Resume Id */
            resume_id?: string | null;
            /**
             * Batch Size
             * @default 5
             */
            batch_size: number;
            /** Min Match Score Override */
            min_match_score_override?: number | null;
            /** Max Experience Years Override */
            max_experience_years_override?: number | null;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Schedule Cron */
            schedule_cron?: string | null;
        };
        /** PipelineResponse */
        PipelineResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Resume Id */
            resume_id: string | null;
            /** Site */
            site: string;
            /** Query */
            query: string;
            /** Locations */
            locations: unknown[];
            /** Filters */
            filters: {
                [key: string]: unknown;
            };
            /** Batch Size */
            batch_size: number;
            /** Min Match Score Override */
            min_match_score_override: number | null;
            /** Max Experience Years Override */
            max_experience_years_override: number | null;
            /** Enabled */
            enabled: boolean;
            /** Schedule Cron */
            schedule_cron: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Updated At */
            updated_at: string | null;
        };
        /**
         * PipelineUpdateRequest
         * @description All fields optional — only what's provided gets updated
         *     (Repository.update_pipeline is already a partial update).
         */
        PipelineUpdateRequest: {
            /** Name */
            name?: string | null;
            /** Site */
            site?: string | null;
            /** Query */
            query?: string | null;
            /** Locations */
            locations?: string[] | null;
            /** Filters */
            filters?: {
                [key: string]: unknown;
            } | null;
            /** Resume Id */
            resume_id?: string | null;
            /** Batch Size */
            batch_size?: number | null;
            /** Min Match Score Override */
            min_match_score_override?: number | null;
            /** Max Experience Years Override */
            max_experience_years_override?: number | null;
            /** Enabled */
            enabled?: boolean | null;
            /** Schedule Cron */
            schedule_cron?: string | null;
        };
        /** RejectedJobResponse */
        RejectedJobResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Scrape Run Id
             * Format: uuid
             */
            scrape_run_id: string;
            /**
             * Pipeline Id
             * Format: uuid
             */
            pipeline_id: string;
            /** Title */
            title: string;
            /** Company */
            company: string;
            /** Link */
            link: string;
            /** Match Score */
            match_score: number | null;
            /** Reason */
            reason: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ResumeDetailResponse
         * @description Includes raw_text — omitted from the list response since it can run
         *     to thousands of characters and the list view never needs it.
         */
        ResumeDetailResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Filename */
            filename: string;
            /** Parsed Profile */
            parsed_profile: {
                [key: string]: unknown;
            } | null;
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
            /** Raw Text */
            raw_text: string;
        };
        /** ResumeResponse */
        ResumeResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Filename */
            filename: string;
            /** Parsed Profile */
            parsed_profile: {
                [key: string]: unknown;
            } | null;
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
        };
        /** ScrapeRunResponse */
        ScrapeRunResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Pipeline Id
             * Format: uuid
             */
            pipeline_id: string;
            /** Status */
            status: string;
            /** Cancel Requested */
            cancel_requested: boolean;
            /** Config Snapshot */
            config_snapshot: {
                [key: string]: unknown;
            };
            /** Jobs Seen */
            jobs_seen: number;
            /** Jobs Saved */
            jobs_saved: number;
            /** Jobs Rejected */
            jobs_rejected: number;
            /** Errors */
            errors: unknown[];
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
        };
        /** ScrapeTriggerRequest */
        ScrapeTriggerRequest: {
            /**
             * Pipeline Id
             * Format: uuid
             */
            pipeline_id: string;
            /**
             * Limit
             * @description Cap the number of raw jobs scraped, for manual testing
             */
            limit?: number | null;
        };
        /** ScrapeTriggerResponse */
        ScrapeTriggerResponse: {
            /** Enqueued */
            enqueued: boolean;
            /** Job Id */
            job_id: string;
            /**
             * Pipeline Id
             * Format: uuid
             */
            pipeline_id: string;
        };
        /** ScraperCredentialResponse */
        ScraperCredentialResponse: {
            /** Site */
            site: string;
            /**
             * Configured
             * @description Whether a value has been set — the full value itself is never echoed back.
             */
            configured: boolean;
            /**
             * Masked Value
             * @description Last 4 characters only (e.g. '••••••wxyz') — enough to recognize which cookie is stored without exposing it.
             */
            masked_value?: string | null;
            /**
             * Last Check Status
             * @description 'valid' | 'invalid' | 'error' | null if never checked.
             */
            last_check_status?: string | null;
            /** Last Checked At */
            last_checked_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /** ScraperCredentialUpdateRequest */
        ScraperCredentialUpdateRequest: {
            /** Value */
            value: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_jobs_jobs_get: {
        parameters: {
            query?: {
                min_score?: number | null;
                max_score?: number | null;
                min_experience?: number | null;
                max_experience?: number | null;
                /** @description Partial match */
                company?: string | null;
                /** @description Partial match */
                title?: string | null;
                /** @description Partial match */
                location?: string | null;
                /** @description new|saved|applied|interview|offer|rejected|deleted */
                status?: string | null;
                seniority?: string | null;
                remote_policy?: string | null;
                has_description?: boolean | null;
                has_score?: boolean | null;
                /** @description FR-1A.6: scope results to one pipeline */
                pipeline_id?: string | null;
                /** @description Comma-separated: match_score,experience,scraped_at,company,title */
                sort_by?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_jobs_before_jobs_delete: {
        parameters: {
            query: {
                /** @description Permanently delete jobs posted on/before this date (YYYY-MM-DD) */
                before_date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkDeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_stats_jobs_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatsResponse"];
                };
            };
        };
    };
    count_jobs_before_jobs_count_before_get: {
        parameters: {
            query: {
                /** @description Count jobs on/before this date (YYYY-MM-DD) */
                before_date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobCountResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_job_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_job_status_jobs__job_id__status_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobStatusUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatusUpdateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_scrape_scrape_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScrapeTriggerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScrapeTriggerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_scrape_runs_scrape_runs_get: {
        parameters: {
            query?: {
                pipeline_id?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScrapeRunResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scrape_run_scrape__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScrapeRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_scrape_run_scrape__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScrapeRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_resumes_resumes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeResponse"][];
                };
            };
        };
    };
    create_resume_resumes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_resume_resumes_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_resume_resumes__resume_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resume_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_resume_resumes__resume_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resume_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_update_resume_resumes__resume_id__put"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_resume_resumes__resume_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resume_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_pipelines_pipelines_get: {
        parameters: {
            query?: {
                enabled_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_pipeline_pipelines_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PipelineCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pipeline_pipelines__pipeline_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pipeline_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_pipeline_pipelines__pipeline_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pipeline_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PipelineUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_pipeline_pipelines__pipeline_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pipeline_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rejected_jobs_pipelines__pipeline_id__rejected_jobs_get: {
        parameters: {
            query?: {
                scrape_run_id?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                pipeline_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RejectedJobResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_scrape_runs_pipelines__pipeline_id__scrape_runs_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pipeline_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeletedCountResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_llm_setting_settings_llm_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LLMSettingResponse"];
                };
            };
        };
    };
    update_llm_setting_settings_llm_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LLMSettingUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LLMSettingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scraper_credential_settings_scraper_credentials__site__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScraperCredentialResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_scraper_credential_settings_scraper_credentials__site__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScraperCredentialUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScraperCredentialResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_on_demand_feature_features__feature___job_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feature: string;
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["FeatureRequestBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_csv_export_csv_get: {
        parameters: {
            query?: {
                pipeline_id?: string | null;
                /** @description Only export matched jobs */
                has_score?: boolean;
                min_score?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_excel_export_excel_get: {
        parameters: {
            query?: {
                pipeline_id?: string | null;
                /** @description Only export matched jobs */
                has_score?: boolean;
                min_score?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
